---
- name: Configure httpd web server
  hosts: web_servers
  become: true
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Create index.html file
      copy:
        content: |
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Nautilus Sample Page</title>
              <style>
                  body {
                      font-family: Arial, sans-serif;
                      text-align: center;
                      padding: 50px;
                      background-color: #f4f4f4;
                  }
                  h1 {
                      color: #333;
                  }
                  p {
                      color: #666;
                  }
              </style>
          </head>
          <body>
              <h1>This is a sample page, created using Ansible!</h1>
              <p>Welcome to my project!</p>
          </body>
          </html>
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: "0655"
